### ISSUE TITLE
Move vON into the addon

### ISSUE THREAD

**Issue by vercas** [Xandaros/evolve#125]
Since about an hour ago, I'm on a quest to stop people from misusing vON.

There are several versions in use right now - conflicting versions.
Putting it in the autorun folder like this will just overwrite it or let it be overwritten.

Move it to *lua/ev_von.lua* or something like that and include it manually.
Change lines 605-608 to have *evolve.von* instead of *von* and use it like that.
(since the project is open source, you can freely do that)

I'm asking you this because pretty much everyone (except me..?) seems to shove vON in their autorun folder.
Now there are tens (hopefully JUST tens) of addons with conflicting versions, and people keep reporting problems to me, when it's not my fault nor theirs.

**Comment by Xandaros** [comment]
Ah, sorry if that caused you trouble, I will fix it right away.
I do wonder, though... why has nobody contacted me? Since evolve is clearly at fault here...

Wiremod is doing the same, btw. I just did it the way they did. Usually a bad idea, should have known better :)

(By the way, evolve has some problems with a vON encoded file getting corrupted and I noticed there are newer versions of vON available. Is it a problem with vON that was fixed? Can't track it down and I have no idea how to reproduce it.)

**Comment by vercas** [comment]
Regarding Wiremod, Divran [fixed it](https://github.com/wiremod/wire/commit/29d027481afd9f614d1575bb3f229e940c4fddf6) just a few hours ago.

Regarding the corruption, yes, there is a major bug in your specific version (which is also pre-GitHub).
More specifically, strings ending in a backslash will break the deserializing operation.

I recommend you try [the latest version](https://github.com/vercas/vON/blob/master/von.lua) for a while.

**Comment by Xandaros** [comment]
It broke for me, so I just assumed it breaks for everything.
I moved all data files to a different location, so they don't get corrupted if people upgrade, but I haven't put any automatic conversion in.
I might supply a script for people to convert to the new vON, but probably not until the first complaint comes in :P

I hope this finally fixes #119 since that has been bugging me for a while now. Many thanks for showing me how old the vON version is we are using :)

**Comment by vercas** [comment]
Well, you can easily load two versions of vON.
If you don't store any GMod-specific types (angles, vectors, entities), you can even make it run outside GMod.
