### ISSUE TITLE
Rank via Playertime?

### ISSUE THREAD

**Issue by doxlulzem** [Xandaros/evolve#131]
I guess this is an enhancement?
So, I know that on The Abyss servers you get ranked on playertime, and I also know that is because Matt modded Evolve 'till it was practically not Evolve. And I think that would be something really useful. Considering my server has ranks of the British Army that would seem logical (7 ranks excluding owner) that I have an automatic system. So is this an actual plugin thingy and if not, it really needs to be added!

**Comment by Xandaros** [comment]
@Divran made such a plugin ages ago. It still needs to be updated to the "new" gmod, though :/
http://divranspack.googlecode.com/svn/trunk/%20divranspack/Divrans%20Evolve%20Plugins/sv_rankovertime.lua

If you port it, be sure to let me know. This is not something that I want in the official evolve, but since evolve is heavily plugin based, it is rather easy to install new ones.

**Comment by doxlulzem** [comment]
Nice. All I need now is to know what to do with it...

**Comment by Xandaros** [comment]
Put it in the plugins directory? :P
But, as I said, it will probably not work anymore. Needs to be fixed.

**Comment by Divran** [comment]
Just want to point out that since google code is getting shut down, they've offered to move all your stuff over to github, so I did. https://github.com/Divran/divranspack

**Comment by doxlulzem** [comment]
Another question: Is rank by score possible? Like 10 kills or something?

**Comment by Divran** [comment]
rank by absolutely anything is possible. You just have to make a plugin for it first
