### ISSUE TITLE
A way to change playtime?

### ISSUE THREAD

**Issue by Jcdiem** [Xandaros/evolve#143]
There was a glitch on my server that set player's playtime to random numbers, negative and very high positive. This seems to have stopped, but I would like to know if there is any way I can change the playtime so I can at least set them to 0 hours. This is sort of a problem since my server is based on time for ranks.

**Comment by Xandaros** [comment]
That glitch will probably appear again and I still have no bloody clue what causes it, sorry.
I would advise against the use of ranks based on time, glitches or not, but I guess that is your decision :)

As to your actual question, there is currently no easy way to change playtime, short of changing it in the vON file manually (`data/evolve/playerinfo.txt`) Make a backup before you attempt changing anything, as it is fairly easy to corrupt the file. Make sure you use an editor that doesn't change the newlines, encoding or otherwise (If you use Linux/Mac, that applies to probably every single editor. If you use Windows, use something like Notepad++)

I will leave this issue open, as a plugin that allows you to change playtime would probably be useful.

**Comment by jonfrog** [comment]
Alright, thanks. I'll get back to you on if it worked or not.

**Comment by Jcdiem** [comment]
Closing, as the file can be edited to change playertime. Even if it does take me 6 years to do it.
