### ISSUE TITLE
Show Player Names in Prop Hunt

### ISSUE THREAD

**Issue by Xer0n** [Xandaros/evolve#74]
I am running two servers using the Prop Hunt game mode, and I have disabled 'Show Player Names' for all of the rankings except for Owner and the players can still view the player names of the hiding props when looking at them.  Please correct me if I'm wrong, but isn't this option used to remove that?  If so, it's not working correctly and makes the game kind of unfair.  If this option isn't designed for this, can you enlighten me on what it does?

If the option is for the names above the head, is there a way to disable the name in red letters while looking at a prop/player?

Thanks,
|TBB| Xer0n_

**Comment by neighbz** [comment]
Wow, OP states they tried using an option on the add-on to fix an issue they were having on their servers, it didn't work, and asks if anyone knew if the option they chose was even meant to fix what they were trying to and if there is an option to fix the issue they were still having. All they get in reply are two people telling them that this isn't a "help desk", and another backing up the douchey-reply and adding in to not ask questions unless for issues they are having with the add-on unless they have tested it when the add-on was on, when it was off, and done research on it. Basically saying, "Hey, I know this is a forum to state issues you are having that may be caused by my add-on, but unless you have done thorough testing on it, looked up every link on every page that shows up from your browser search, and found a way to fix it, do not post anything. I completely get not being obligated to find fixes for issues not caused by the add-on. I completely understand why, if you didn't know a solution to a question someone asked, that isn't 100% verified to be caused by the add-on, that there is nothing you can do to help and no need to reply. On the other hand, I really don't get why both people who replied went the route of, basically, talking down to the OP because they asked a question they weren't sure the add-on caused or not and if it didn't still requested that any readers let them know of a fix to the problem. How hard would it have been to say, "Hey, I could see how that would be an issue for the people playing on your server, and why it's something you would want to fix. However, this add-on wouldn't cause that to happen and wouldn't be able to fix the issue, either. It must be something wrong with the game-type's files or the game itself. I don't personally know how you would fix that, so you are best off trying to find a solution somewhere else online. If you could post some pictures showing us what you are talking about we could try and see if there was anyway our program would be able to fix this issue. Sorry we couldn't be more help to you." 1) it won't discourage the OP from asking elsewhere online for someone with the knowledge to fix it/those that see this post before any others and end up deciding not to post what they were going to originally because they feel like they would just be treated the same. 2) seeing if there was a way your add-on would be updated in a wy to be able to fix this issue would not only help this person out, but every single other person having the same problem. Meaning the number of people using your program would multiply a ton. Aka, responding in a better manner, being more helpful, and realizing that since this person's issue wasn't caused by your program, and must be the game itself, means that every single other person playing the game mode OP was talking about has the same issue, and finding a fix for the issue would only result with you receiving that much more traffic/downloads. Not to mention there is already more than enough assholes online. No need to contribute by adding to that number.

**Comment by naclark46168** [comment]
You can be upset over the feedback from the comment, as i agree it should be worded differently, but this was closed 2 years ago. "This isnt a help desk" and this certainly isnt a place to complain about a small argument 2 years ago, you spent probably 20 minutes trying figure out what to say, and probably after the first 20 words, i thought oh this is a rant, im not going to read the whole thing. This is git hub, a place where people come to get codes, help with codes, and publish codes, not to go on a "he was treated unfairly so let me speak my mind. Yes i realize most people wont read this, but i could care less.

**Comment by Xandaros** [comment]
@neighbz I am not sure what you are on about. First oft all, @MrFaul is not an official contributor and I am not going to censor him just because he used some harsh words.
And second of all - why are you including me in this? All I said was that he should try it again without evolve. If the problem does not persist, it is evidently caused by evolve and he should open another issue.

I did not read the whole thing, btw. Breaking it up into paragraphs might help with getting people to read your comment.

**Comment by MrFaul** [comment]
lol

Never thought somebody would throw a tantrum for that. And yes it was harsh
but hey, it is still the truth.

And posting that on facepunch would draw far more attention in comparison
to git...... and attention was his goal he stated that clearly.

So suck it up and take it like a man, the world is full of shitholes
including me.
And trust me I, I'm one of the kind ones.....
Am 04.08.2015 21:07 schrieb "Xandaros" <notifications@github.com>:
